name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Matikan semua statistik bawaan GitHub yang bikin duplikat
          base: ""
          
          # ==========================================
          # 1. GAMING SHOWCASE (STEAM)
          # ==========================================
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "https://steamcommunity.com/profiles/76561199549509683/"
          plugin_steam_sections: favorites, recently-played
          plugin_steam_games_limit: 4
          
          # ==========================================
          # 2. ANIME & WAIFU SHOWCASE (ANILIST)
          # ==========================================
          plugin_anilist: yes
          plugin_anilist_user: "Blancwithkuroo"
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 2 # Nampilin karakter favorit/waifu